config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: :show
  resources :rankings, only: :index
  get '/search/incremental_search', to: 'search#incremental_search' #この定義はsearch#showより上に書く
  resources :search, only: :show
  resources :genres, only: [:index,:show,:new,:create]
  resources :artists, only: [:new,:create,:show]
  resources :albums, only: [:new,:create,:show]
  resources :songs, only: [:index,:new,:create] do
    collection do
      get 'play'
      post 'set_music_info'
    end
  end
  resources :follows, only: [:create,:destroy]
  resources :fav_songs, only: [:create,:destroy]
  resources :fav_albums, only: [:create,:destroy]
  resources :playlists, only: [:create,:destroy,:show,:index]
  resources :playlist_songs, only: [:create,:destroy]
  resources :trend, only: :index
  root 'songs#index'
  get '*anything', to: 'errors#routing_error'
end

app/models/fav_song.rb
class FavSong < ActiveRecord::Base
  belongs_to :user
  belongs_to :song
end

app/controllers/fav_songs_controller.rb
class FavSongsController < ApplicationController

  def create
    @song = Song.find(params[:format])
    current_user.fav_songs.create(song_id: @song.id)
  end
  def destroy
    @song = Song.find(params[:id])
    fav_song = current_user.fav_songs.find_by(song_id:@song.id)
    fav_song.destroy
  end
end

app/views/fav_songs/_like_button.html.haml
-if current_user.f_songs.find_by(id:song.id)
  =link_to fav_song_path(song), method: :delete, remote: true do
    = embedded_svg("favorite.svg")
-else
  =link_to fav_songs_path(song), method: :post, remote: true do
    = embedded_svg("un_favorite.svg")

app/views/fav_songs/create.js.haml
$('#fav_song_#{@song.id}').html("#{ j(render "fav_songs/like_button", song:@song ) }");

app/views/fav_songs/destroy.js.haml
$('#fav_song_#{@song.id}').html("#{ j(render "fav_songs/like_button", song:@song ) }");