config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: :show
  resources :rankings, only: :index
  get '/search/incremental_search', to: 'search#incremental_search' #この定義はsearch#showより上に書く
  resources :search, only: :show
  resources :genres, only: [:index,:show,:new,:create]
  resources :artists, only: [:new,:create,:show]
  resources :albums, only: [:new,:create,:show]
  resources :songs, only: [:index,:new,:create] do
    collection do
      get 'play'
      post 'set_music_info'
    end
  end
  resources :follows, only: [:create,:destroy]
  resources :fav_songs, only: [:create,:destroy]
  resources :fav_albums, only: [:create,:destroy]
  resources :playlists, only: [:create,:destroy,:show,:index]
  resources :playlist_songs, only: [:create,:destroy]
  resources :trend, only: :index
  root 'songs#index'
  get '*anything', to: 'errors#routing_error'
end

app/models/fav_album.rb
class FavAlbum < ActiveRecord::Base
  belongs_to :user
  belongs_to :album
end

app/controllers/fav_albums_controller.rb
class FavAlbumsController < ApplicationController

  def create
    @album = Album.find(params[:format])
    current_user.fav_albums.create(album_id: @album.id)
  end
  def destroy
    @album = Album.find(params[:id])
    fav_album = current_user.fav_albums.find_by(album_id:@album.id)
    fav_album.destroy
  end
end

app/views/fav_albums/_like_button.html.haml
-if !user_signed_in?
  = button_to "お気に入り", 'javascript:void(0)', class: "btn btn-lg btn-default",data:{target:"#login_modal",toggle:"modal"}
-elsif current_user.f_albums.find_by(id:album.id)
  = button_to "お気に入り中", fav_album_path(album), method: :delete, remote: true, class: "btn btn-lg btn-default"
-else
  = button_to "お気に入り", fav_albums_path(album), method: :post, remote: true, class: "btn btn-lg btn-default"

app/views/fav_albums/create.js.haml
$('#album_like_button').html("#{ j(render 'fav_albums/like_button', album: @album ) }");

app/views/fav_albums/destroy.js.haml
$('#album_like_button').html("#{ j(render 'fav_albums/like_button', album: @album ) }");