config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: :show
  resources :rankings, only: :index
  get '/search/incremental_search', to: 'search#incremental_search' #この定義はsearch#showより上に書く
  resources :search, only: :show
  resources :genres, only: [:index,:show,:new,:create]
  resources :artists, only: [:new,:create,:show]
  resources :albums, only: [:new,:create,:show]
  resources :songs, only: [:index,:new,:create] do
    collection do
      get 'play'
      post 'set_music_info'
    end
  end
  resources :follows, only: [:create,:destroy]
  resources :fav_songs, only: [:create,:destroy]
  resources :fav_albums, only: [:create,:destroy]
  resources :playlists, only: [:create,:destroy,:show,:index]
  resources :playlist_songs, only: [:create,:destroy]
  resources :trend, only: :index
  root 'songs#index'
  get '*anything', to: 'errors#routing_error'
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user
  belongs_to :artist
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  def create
    @artist = Artist.find(params[:format])
    current_user.follows.create(artist_id:@artist.id)
  end

  def destroy
    @artist = Artist.find(params[:id])
    follow = current_user.follows.find_by(artist_id:@artist.id)
    follow.destroy
  end
end

app/views/follows/_follow_button.html.haml
-if !user_signed_in?
  = button_to "フォロー", 'javascript:void(0)', class: "btn btn-lg btn-default",data:{target:"#login_modal",toggle:"modal"}
-elsif current_user.follows.find_by(artist_id: artist.id)
  = button_to "フォロー中",follow_path(artist), method: :delete, remote: true,class:"btn btn-lg btn-default"
-else
  = button_to "フォロー", follows_path(artist), method: :post, remote: true, class: "btn btn-lg btn-default"

app/views/follows/create.js.haml
$('#follower-count').text("#{@artist.follower.count}人のフォロワー");
$('#follow-button').html("#{ j(render 'follows/follow_button', artist: @artist ) }");

app/views/follows/destroy.js.haml
$('#follower-count').text("#{@artist.follower.count}人のフォロワー");
$('#follow-button').html("#{ j(render 'follows/follow_button', artist: @artist ) }");