config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: :show
  resources :rankings, only: :index
  get '/search/incremental_search', to: 'search#incremental_search' #この定義はsearch#showより上に書く
  resources :search, only: :show
  resources :genres, only: [:index,:show,:new,:create]
  resources :artists, only: [:new,:create,:show]
  resources :albums, only: [:new,:create,:show]
  resources :songs, only: [:index,:new,:create] do
    collection do
      get 'play'
      post 'set_music_info'
    end
  end
  resources :follows, only: [:create,:destroy]
  resources :fav_songs, only: [:create,:destroy]
  resources :fav_albums, only: [:create,:destroy]
  resources :playlists, only: [:create,:destroy,:show,:index]
  resources :playlist_songs, only: [:create,:destroy]
  resources :trend, only: :index
  root 'songs#index'
  get '*anything', to: 'errors#routing_error'
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user

  has_many :playlist_songs, dependent: :destroy
  has_many :songs, through: :playlist_songs
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
    @playlists = Playlist.where("private = ?", false)
    @new_playlists = Playlist.where("private = ?", false).order(created_at: :desc)
  end

  def create
    #params[:data]はこんなデータ {"data"=>{"title"=>"test_title", "desc"=>"test_desc", "public_state"=>"publish"}}
    title = params[:data][:title]
    desc = params[:data][:desc]
    public_state = params[:data][:public_state]
    @playlist = current_user.playlists.create(name:title,description:desc)
    @playlist.private = false if public_state == "publish"
    @playlist.private = true if public_state == "private"
    @playlist.save
    @myplaylists = current_user.playlists    #マイページ、ドロワーのプレイリストの表示更新に使う
  end

  def show
    @playlist = Playlist.find(params[:id])
    @songs_id = @playlist.songs.map{|s|s.id}
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy
  end
end

app/views/playlists/_drawer.html.haml
%nav.drawer-nav{:role => "navigation"}
  %ul.drawer-menu
    .title
      %h5 プレイリスト選択
      = link_to 'javascript:void(0)',id:"drawer-close" do
        = embedded_svg("close.svg")
    %hr.line
    = link_to 'javascript:void(0)', class:"drawer-menu-item", data:{target:"#playlist_modal",toggle:"modal"} do
      %span.glyphicon.glyphicon-plus
      プレイリストを作成
    #render_playlists_for_drawer
      - current_user.playlists.each do |playlist|
        = render "playlists/link",playlist:playlist

app/views/playlists/_link.html.haml
%li
  %a.drawer-menu-item{ href:"javascript:void(0)",onclick:"add_playlist(" + playlist.id.to_s + "); return false;" }= playlist.name

app/views/playlists/_playlist.html.haml
.thumb
  %figure
    = link_to playlist_path(playlist) do
      - if playlist.songs.count != 0
        =image_tag(playlist.songs[0].album.album_image.url,class:"thumb_image")
        %figcaption
          = image_tag(playlist.songs[0].album.album_image.url,class:"thumb_image thumb_caption")
      - else
        =image_tag("playlist_default.png",class:"thumb_image")
        %figcaption
          = image_tag("playlist_default.png",class:"thumb_image thumb_caption")
  %h6= link_to playlist.name, playlist_path(playlist)
  - if playlist.private?
    %h6.gray 自分のみ
  - else
    %h6.gray 公開

app/views/playlists/create.js.haml
//プレイリストモーダルを閉じる
$('.close').click();
//フラッシュがすでにあるなら書き換え。ないならフラッシュ要素を作ってテキストを代入
if($('.alert-info')[0]){
$('.alert-info').text("プレイリスト「#{@playlist.name}」を作成しました。");
}else{
$('[data-pjax-container=""]').before("<div class=alert-info></div>")
$('.alert-info').text("プレイリスト「#{@playlist.name}」を作成しました。");
}
//マイページのマイプレイリストの表示を更新
$('#render_playlists_for_mypage').html("#{ j(render @myplaylists ) }");
//ドロワーのマイプレイリストの表示を更新
var myplaylists = "#{@myplaylists.to_json}";
myplaylists = JSON.parse(myplaylists.replace(/&quot;/g,'"'));
var html = '';
for (var i = 0; i < myplaylists.length; i++) {
html += '<li><a class="drawer-menu-item" href="javascript:void(0)" onclick="add_playlist(' + myplaylists[i].id + '); return false;">' + myplaylists[i].name + '</a></li>';
}
$('#render_playlists_for_drawer').html(html);

app/views/playlists/destroy.js.haml
//ユーザーページに移動
var url = '/users/' + "#{current_user.id}";
var a = $("<a></a>",{href: url,"id": "tmp_a"});
$('body').prepend(a);
$('#tmp_a').click();
$('#tmp_a').remove();
//モーダルのオーバーレイの削除
$('.modal-backdrop').remove();

app/views/playlists/index.html.haml
.container
  .trend-title
    = embedded_svg("public_playlists.svg")
    %h2.txt みんなのプレイリスト
  %ul.nav.nav-tabs
    %li.active
      =link_to "トレンド","#trend", data: { toggle: 'tab' }
    %li
      =link_to "最新","#timeline", data: { toggle: 'tab' }
  /トレンド
  .tab-content
    .tab-pane.active#trend
      .thumb-container
        - @playlists.each do |playlist|
          = render partial: "songs/everyone_playlist", locals: {playlist: playlist}
  /最新
  .tab-content
    .tab-pane#timeline
      .thumb-container
        - @new_playlists.each do |playlist|
          = render partial: "songs/everyone_playlist", locals: {playlist: playlist}

app/views/playlists/show.html.haml
.container.show_page
  .row.info_container
    .col-md-3
      - if @playlist.songs.count != 0
        = image_tag @playlist.songs[0].album.album_image.url
      - else
        = image_tag "playlist_default.png"
    .col-md-9
      %h2.name= @playlist.name
      .container.info
        .row
          .col-md-2.col-xs-6 作成者
          .col-md-2.col-xs-6= @playlist.user.name
        .row
          .col-md-2.col-xs-6 ソング
          .col-md-2.col-xs-6= "#{@playlist.songs.count}曲"
        .row
          .col-md-2.col-xs-6 再生時間
          .col-md-2.col-xs-6= album_play_time(@playlist)
        .row
          - if @playlist.private?
            .col-md-2.col-xs-6.public_state 自分のみ
          - else
            .col-md-2.col-xs-6.public_state 公開
        .row.description
          .col-md-2.col-xs-6= @playlist.description
        - if user_signed_in? && current_user == @playlist.user
          .row
            .col-md-2.col-xs-6
              %btn.btn.btn-default{data:{target:"#playlist_destroy_modal",toggle:"modal"}}
                %span.glyphicon.glyphicon-trash
                リストを削除
  - if @playlist.songs.count != 0
    %table.table(data-musics-id='#{@songs_id}')
      - @playlist.songs.each.with_index(1) do |song,i|
        %tr{ id: song.id }
          %td
            = i
          %td
            %figure.figure_table
              =image_tag(song.album.album_image.url,class:"thumb_image")
              %figcaption
                = link_to album_path(song.album) do
                  = image_tag(song.album.album_image.url,class:"thumb_image thumb_caption")
                = link_to 'javascript:void(0)',onclick:"play_music(" + song.id.to_s + "); return false;", class:"tr-a-play", data: {song_id: song.id} do
                  = embedded_svg("play_button_mini.svg",class:"play-trigger")
          %td= song.name
          %td= link_to song.album.artist.name, artist_path(song.album.artist)
          %td= song_play_time(song.length)
          %td{ id: "fav_song_#{song.id}" }
            -if user_signed_in?
              = render "fav_songs/like_button", song:song
            -else
              = link_to 'javascript:void(0)',data:{target:"#login_modal",toggle:"modal"} do
                = embedded_svg("un_favorite.svg")
          -if user_signed_in?
            %td.drawer-trigger
              = link_to 'javascript:void(0)' do
                = embedded_svg("check.svg")
          -else
            %td
              = link_to 'javascript:void(0)',data:{target:"#login_modal",toggle:"modal"} do
                = embedded_svg("check.svg")
          %td= song.play_count
  - else
    .content_none
      プレイリストに曲が入っていません。好きな曲を追加してプレイリストを作ろう！
//プレイリスト削除モーダル
#playlist_destroy_modal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body{:style => "display: flex; justify-content: center;"}
        .content
          %h4 このプレイリストを削除してもよろしいですか？
      .modal-footer
        .modal_btn_wrapper
          %button.btn.btn-primary.btn-lg.gray{"data-dismiss" => "modal"} キャンセル
          = link_to playlist_path(@playlist), method:"delete", onclick:"$('.modal-header > .close').click(); return false;", remote: true, data:{skip_pjax: ''} do
            %button.btn.btn-primary.btn-lg.green.playlist_destroy_btn 削除